name: Build Deploy and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: './src/package-lock.json'
    - name: Install dependencies
      run: npm install 
    - name: Run integration tests
      run: npm run test:api
    
  deploy-app:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

  run-e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    needs: deploy-app
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: './src/package-lock.json'
    - name: Install npm dependencies
      run: npm install
    - name: Setup Playwright
      run: npx playwright install
    - name: Run e2e tests
      run: npm run test:e2e
